### ISSUE TITLE
Possibly use curl and wget for downloads - whatever is available

### ISSUE THREAD

**Issue by GitMensch** [shamrice/COBOL-RSS-Reader#5]
This would make this piece of software a bit more portable.
For an idea see https://sourceforge.net/p/gnucobol/code/HEAD/tree/trunk/tests/cobol85/Makefile.am

**Comment by GitMensch** [comment]
After the bunch of changes it would be possibly reasonable to have a new release, what do you think?

**Comment by shamrice** [comment]
Thanks. That's a fantastic idea! I plan on finishing up the related auto configuration related changes (#10 #11 #12 ) in the next week. Once these are completed, I'll tag a new release.
